### PR TITLE
chapter 0 ok in browser

### PR DESCRIPTION
**Pull request by pachadotdev**
chapter 0 ok in browser

### CODE REVIEW

**Comment by jtleek** [comment]
Can you give me some idea why this change is needed? Sorry just trying to figure it out!

**Comment by pachamaltese** [comment]
Yes, because when I open the html it shows nothing for figure, if I revert
the order the html shows the plot.


—————

*Mauricio Vargas Sepúlveda 帕夏*

2016-07-18 14:20 GMT-03:00 Jeff L. <notifications@github.com>:

**Comment by jtleek** [comment]
Ok thanks

**Comment by pachamaltese** [comment]
I just found that issue when showing the example to my class and then...
WHAM ! no plot at all in the html file

—————

*Mauricio Vargas Sepúlveda 帕夏*

2016-07-18 14:21 GMT-03:00 Mauricio Vargas <mvargassepulveda@gmail.com>:

**Pull request merged**
