### PR TITLE
minor refactoring of data

### PR DESCRIPTION
**Pull request by ptoche**
As pointed out by Zach, my previous pull request had problems with the code of chapter 5 data, caused by some incomplete renaming of variables and incomplete reconversion from long to wide forms of some dataframes. 

I have just run both the 'dataFiguresTables.Rnw'  part and 'slidesFigures.Rnw' and I didn't see any error messages and the figures came out fine. 

On second thoughts, maybe it would be best to rename to 'dataFiguresTables.R' and drop the 'chunk' insertion code at the top and bottom of that file, to avoid confusion. Let me know what you think, if anything. 

Cheers for now.

### CODE REVIEW

**Comment by stedy** [comment]
I am having trouble merging this. Would you mind making a fresh pull and then submitting a new request?

**Comment by ptoche** [comment]
I've done my best, but I didn't really know what I was doing. I hope the problem is solved now. Let me know. Otherwise, maybe just delete the whole "Slides" directory and I create a new repository and we link them somehow. Sounds easier, as I have zero github competence.

**Comment by stedy** [comment]
Looks okay!

**Comment by ptoche** [comment]
Great, thanks!

**Pull request merged**
